# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myquestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', help_text='标题', max_length=64)),
                ('create_date', models.DateTimeField(help_text='创建时间')),
                ('deadline', models.DateTimeField(help_text='截止时间')),
                ('state', models.IntegerField(default=0, help_text='状态,0-->草稿,1-->待审核,2-->审核失败,\n                                                        3-->审核成功,4-->发布成功')),
                ('quantity', models.IntegerField(default=1, help_text='发布数量')),
                ('free_count', models.IntegerField(default=1, help_text='可用问卷数量')),
                ('customer', models.ForeignKey(help_text='客户信息', on_delete=django.db.models.deletion.CASCADE, to='Myquestion.Customer')),
            ],
        ),
    ]
