# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myquestion', '0003_question_questionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='审核时间')),
                ('comment', models.TextField(help_text='审核批注')),
                ('questionnaire', models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='Myquestion.Questionnaire')),
            ],
        ),
    ]
