# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myquestion', '0004_questionnairecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='参与时间')),
                ('is_done', models.BooleanField(default=False, help_text='是否已经完成')),
                ('questionnaire', models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='Myquestion.Questionnaire')),
                ('userinfo', models.ForeignKey(help_text='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, to='Myquestion.UserInfo')),
            ],
        ),
    ]
