# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myquestion', '0005_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='选项', on_delete=django.db.models.deletion.CASCADE, to='Myquestion.QuestionItem')),
                ('userinfo', models.ForeignKey(help_text='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, to='Myquestion.UserInfo')),
            ],
        ),
    ]
